### PR TITLE
make plugin compatible with Winter.Blog plugin as well

### PR DESCRIPTION
**Pull request by mjauvin**

### CODE REVIEW

**Comment by jbh** [comment]
Thanks.

**Comment by mjauvin** [comment]
That was quick! :)

**Comment by djshadow** [comment]
Still getting this error when I go to the settings page and try to save the settings

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'brizzynovel.rainlab_blog_posts' doesn't exist (SQL: select * from `rainlab_blog_posts` where `published` = 1 order by `published_at` desc)

Am setting it up wrong or what?

**Comment by RomainMazB** [comment]
@djshadow Did you correctly patched your installation? As long as there is no new release of the plugin (ie new line into version.yaml file), you won't get any changes through the backend update.

You should manually report the changes @mjauvin made.

**Comment by mjauvin** [comment]
Yeah, just clone the github repo locally and install under `plugins/sobored/rss/`

**Comment by djshadow** [comment]
> Yeah, just clone the github repo locally and install under `plugins/sobored/rss/`

I did that, but I will try it again and see.

**Comment by djshadow** [comment]
It doesn't seem to like me I guess. Still the same error.

**Comment by mjauvin** [comment]
Can you show the loadPosts() method within `Plugin.php` ?

**Comment by djshadow** [comment]
protected function loadPosts()
    {
        $posts = \RainLab\Blog\Models\Post::isPublished()
                     ->orderBy('published_at', 'desc')
                     ->get();

        return $posts;
    }

**Comment by mjauvin** [comment]
You have the right version... where EXACTLY is this happening? Can you also post a screenshot of the error?

**Comment by mjauvin** [comment]
Are you sure the blog plugin is installed and enabled? It's working fine for me.

**Comment by djshadow** [comment]
Lol, you can see the blog tab at the top of the page in the snapshot, so yes, it's working. I'm running it on a live site so everything is working fine. Not sure why this is giving me an issue.

**Comment by djshadow** [comment]
Or I should have installed it using "composer require ..." will that solve it?

**Comment by mjauvin** [comment]
I don't think so.

Did you run `artisan winter:up`?

**Comment by mjauvin** [comment]
Did you install RainLab.Blog or Winter.Blog?

**Comment by mjauvin** [comment]
Maybe a `artisan cache:clear` would help?

**Comment by djshadow** [comment]
Winter.blog
Done winter:up
Done cache:clear

**Comment by mjauvin** [comment]
What version of the Winter modules and library do you have? Try updating it to dev-develop with composer

**Comment by djshadow** [comment]
So the error is fixed now but my rss can't be found https://www.brizzynovel.com/rss.xml

**Comment by djshadow** [comment]
Any help, guys?

**Pull request merged**
